### Doxygen configuration for clockwork-libc

#---------------------------------------------------------------------------
# Project related configuration options
#---------------------------------------------------------------------------
PROJECT_NAME           = "clockwork-libc"
PROJECT_BRIEF          = "C library for SIL testing with Clockwork"
OUTPUT_DIRECTORY       = docs
CREATE_SUBDIRS         = NO

#---------------------------------------------------------------------------
# Build related configuration options
#---------------------------------------------------------------------------
OPTIMIZE_OUTPUT_FOR_C  = YES
EXTRACT_ALL            = YES
EXTRACT_STATIC         = YES

WARNINGS               = YES
WARN_IF_UNDOCUMENTED   = YES
WARN_IF_DOC_ERROR      = YES

#---------------------------------------------------------------------------
# Input configuration options
#---------------------------------------------------------------------------
INPUT                  = include lib
FILE_PATTERNS          = *.h *.c
RECURSIVE              = YES

#---------------------------------------------------------------------------
# Preprocessor / macro documentation
#---------------------------------------------------------------------------
ENABLE_PREPROCESSING   = YES
MACRO_EXPANSION        = YES
EXPAND_ONLY_PREDEF     = NO

SKIP_FUNCTION_MACROS   = NO

EXPAND_AS_DEFINED      =
PREDEFINED             =

#---------------------------------------------------------------------------
# HTML output configuration options
#---------------------------------------------------------------------------
GENERATE_HTML          = YES
HTML_OUTPUT            = html

#---------------------------------------------------------------------------
# Misc configuration options
#---------------------------------------------------------------------------
QUIET                  = NO
JAVADOC_AUTOBRIEF      = YES
MULTILINE_CPP_IS_BRIEF = YES
ALWAYS_DETAILED_SEC    = YES