#ifndef CLOCKWORK_ERRORS_H
#define CLOCKWORK_ERRORS_H

#include <stdint.h>

enum {
  ERR_CONN_NO_ERROR = 0,
  ERR_CONN_CONNECTION_FAILED = -1,
  ERR_CONN_DISCONNECTION_FAILED = -2,
  ERR_CONN_INVALID_STATE = -3,
};

#endif